from django.shortcuts import render
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse

from core.models import IscUser, MftUser, Directory, Permission, DirectoryPermissionCode
from .models import Invoice

from jdatetime import datetime as jdt

import logging

logger = logging.getLogger(__name__)


@login_required(login_url='/login/')
def invoice_view(request, *args, **kwargs):
    isc_user = IscUser.objects.get(user=request.user)
    uid = int(request.GET.get('user'))
    mftuser = None
    user_accesses = []

    if request.is_ajax():
        if request.method == 'POST':
            if request.POST.get('invoice') == 'new':
                invoice = Invoice(mftuser=uid, created_by=isc_user, created_at=timezone.now())
                invoice.save()
                sn = invoice.serial_number
                logger.info(f'invoice with serial number {sn} generated by {isc_user.user.username}.')
                response = {
                    'result': 'success',
                    'invoice_number': sn,
                    'jdate': jdt.now().strftime('%Y/%m/%d'),
                    'counter': Invoice.objects.filter(mftuser=uid).count()
                }
            return JsonResponse(data=response, safe=False)

    mftuser = MftUser.objects.get(pk=uid)
    permissions = Permission.objects.filter(user=mftuser, permission__in=[1, 2, 32, 4]).order_by('directory')
    directory_ids = [p['directory'] for p in permissions.values('directory').distinct()]
    for dir_ in Directory.objects.filter(id__in=directory_ids):
        perms = permissions.filter(directory=dir_)
        perms_str = ''
        for p in perms:
            perms_str += f'{DirectoryPermissionCode.objects.get(value=p.permission)}، '
        user_accesses.append({'dir': dir_.relative_path, 'perms': perms_str[:-2]})

    context = {
        'username': str(isc_user.user.username),
        'access': str(isc_user.role.code),
        'mftuser': mftuser,
        'user_accesses': user_accesses
    }
    
    return render(request, 'invoice/invoice.html', context)