# Generated by Django 3.2 on 2022-02-15 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankIdentifierCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='_ISC', max_length=4, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodingType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('absolute_path', models.CharField(max_length=255)),
                ('business', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('bic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bankidentifiercode', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryPermissionCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='READ', max_length=10, unique=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codingtype', to_field='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IscDepartmentCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='ISC-OPR-OPR3-ISSO', max_length=100, unique=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codingtype', to_field='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IscUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscdepartmentcode', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='MftUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('firstname', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('business', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('bic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bankidentifiercode', to_field='code')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuser')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuser')),
                ('directory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.directory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.directorypermissioncode', to_field='code')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mftuser')),
            ],
        ),
        migrations.CreateModel(
            name='IscUserAccessCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='CUSTOMER', max_length=20, unique=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codingtype', to_field='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='iscuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuseraccesscode', to_field='code'),
        ),
        migrations.AddField(
            model_name='iscuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuser'),
        ),
        migrations.AddField(
            model_name='bankidentifiercode',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codingtype', to_field='type'),
        ),
    ]
