# Generated by Django 3.2 on 2022-02-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mftuser',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=9123456789, max_digits=11),
        ),
    ]
