# Generated by Django 3.2 on 2022-02-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220216_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mftuser',
            name='created_by',
            field=models.ForeignKey(default='mojtaba', on_delete=django.db.models.deletion.CASCADE, to='core.iscuser'),
        ),
    ]
