# Generated by Django 3.2 on 2022-02-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mftuser_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mftuser',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.iscuser'),
        ),
    ]
