# Generated by Django 3.2.11 on 2022-02-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mftuser_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mftuser',
            name='password',
            field=models.CharField(default='isc@12345678', max_length=255),
        ),
    ]
