# Generated by Django 3.2.11 on 2022-02-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mftuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankidentifiercode',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='directorypermissioncode',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='iscdepartmentcode',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='iscuseraccesscode',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
