# Generated by Django 3.2.11 on 2022-02-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220228_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='type',
            new_name='ptype',
        ),
    ]
