# Generated by Django 3.2.11 on 2022-02-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_type_permission_ptype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='directory_id',
            new_name='directory',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='user_id',
            new_name='user',
        ),
    ]
