# Generated by Django 3.2.11 on 2022-02-28 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220228_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='mftuser',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
