# Generated by Django 3.1.4 on 2022-04-07 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mftuser_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CustomerAccessCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('code', models.CharField(default='OWNER', max_length=10, unique=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codingtype', to_field='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_on', models.CharField(choices=[(1, 'MftUser'), (2, 'Directory'), (3, 'Permission')], default='MftUser', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customeraccesscode', to_field='code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuser')),
            ],
        ),
    ]
