# Generated by Django 3.1.4 on 2022-04-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220407_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccess',
            name='target_id',
            field=models.IntegerField(default=-1),
        ),
    ]
