# Generated by Django 3.1.4 on 2022-04-07 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customeraccess_target_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccessType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('code', models.CharField(default='MftUser', max_length=10, unique=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codingtype', to_field='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customeraccess',
            name='access_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customeraccesstype', to_field='code'),
        ),
    ]
