# Generated by Django 3.1.4 on 2022-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220407_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccesscode',
            name='code',
            field=models.CharField(default='MftUser', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customeraccesstype',
            name='code',
            field=models.CharField(default='OWNER', max_length=10, unique=True),
        ),
    ]
