# Generated by Django 3.1.4 on 2022-04-07 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220407_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccess',
            name='access_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customeraccesscode', to_field='code'),
        ),
        migrations.AlterField(
            model_name='customeraccess',
            name='access_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customeraccesstype', to_field='code'),
        ),
    ]
