# Generated by Django 3.1.4 on 2022-04-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220407_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='children',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
