# Generated by Django 3.1.4 on 2022-04-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_directory_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
