# Generated by Django 3.1.4 on 2022-05-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_directoryindexcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='index_code',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='core.directoryindexcode', to_field='code'),
        ),
    ]
