# Generated by Django 3.1.4 on 2022-05-20 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_directory_index_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MftUserTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(default='isc@12345678', max_length=255)),
                ('firstname', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.DecimalField(decimal_places=0, default=9123456789, max_digits=11)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('business', models.CharField(default='mft', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('bic', models.ForeignKey(default='_ISC', on_delete=django.db.models.deletion.CASCADE, to='core.bankidentifiercode', to_field='code')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.iscuser')),
            ],
        ),
    ]
