# Generated by Django 3.1.4 on 2022-05-21 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_mftusertemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mftuser',
            old_name='phone',
            new_name='mobilephone',
        ),
        migrations.RemoveField(
            model_name='mftuser',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='mftuser',
            name='business',
        ),
        migrations.AddField(
            model_name='mftuser',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mftuser',
            name='officephone',
            field=models.DecimalField(decimal_places=0, default=12345678, max_digits=8),
        ),
        migrations.AlterField(
            model_name='mftuser',
            name='organization',
            field=models.ForeignKey(default='_ISC', on_delete=django.db.models.deletion.CASCADE, to='core.bankidentifiercode', to_field='code'),
        ),
        migrations.AlterField(
            model_name='mftuser',
            name='password',
            field=models.CharField(default='Isc@12345678', max_length=255),
        ),
    ]
