# Generated by Django 3.1.4 on 2022-05-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220521_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypermissioncode',
            name='code',
            field=models.CharField(default='READ', max_length=20, unique=True),
        ),
    ]
