# Generated by Django 3.1.4 on 2022-05-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20220523_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypermissioncode',
            name='value',
            field=models.IntegerField(default=-1),
        ),
    ]
