# Generated by Django 3.1.4 on 2022-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_directorypermissioncode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mftuser',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mftuser',
            name='home_dir',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='mftusertemp',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mftusertemp',
            name='home_dir',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
