# Generated by Django 3.1.4 on 2022-05-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220523_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='ptype',
        ),
        migrations.AddField(
            model_name='permission',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.directorypermissioncode', to_field='value'),
        ),
        migrations.AlterField(
            model_name='directorypermissioncode',
            name='value',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
