# Generated by Django 3.1.4 on 2022-05-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220528_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='value',
            new_name='permission',
        ),
    ]
