# Generated by Django 3.1.4 on 2022-05-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220528_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mftusertemp',
            name='is_confirmed',
        ),
    ]
