# Generated by Django 3.1.4 on 2022-06-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_customerbank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerbank',
            old_name='access_on',
            new_name='access_on_bic',
        ),
    ]
