# Generated by Django 3.1.4 on 2022-06-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220619_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbank',
            name='created_at',
        ),
    ]
