# Generated by Django 3.2.13 on 2022-06-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_directorypermissioncode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypermissioncode',
            name='code',
            field=models.CharField(default='READ', max_length=20, unique=True),
        ),
    ]
