# Generated by Django 3.2.13 on 2022-06-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_permission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypermissioncode',
            name='value',
            field=models.IntegerField(default=256, unique=True),
        ),
    ]
