# Generated by Django 3.1.4 on 2022-07-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_directorypermissioncode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
