# Generated by Django 3.1.4 on 2022-07-20 05:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20220719_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyToExport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('MftUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mftuser', unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuser')),
            ],
        ),
    ]
