# Generated by Django 3.1.4 on 2022-07-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_readytoexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readytoexport',
            name='MftUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.mftuser'),
        ),
    ]
