# Generated by Django 3.1.4 on 2022-07-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20220720_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readytoexport',
            old_name='MftUser',
            new_name='mftuser',
        ),
    ]
