# Generated by Django 3.1.4 on 2022-07-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20220720_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='readytoexport',
            name='export_path',
            field=models.FileField(default='template.xml', upload_to='exports/'),
        ),
    ]
