# Generated by Django 3.1.4 on 2022-08-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20220726_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission',
            field=models.IntegerField(default=256),
        ),
    ]
