# Generated by Django 3.1.4 on 2022-08-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20220809_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='business',
        ),
        migrations.CreateModel(
            name='OperationBusiness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuser')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('code', models.CharField(default='...', max_length=10, unique=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codingtype', to_field='type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
