# Generated by Django 3.1.4 on 2022-08-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20220822_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='business',
            field=models.ForeignKey(default='NAHAB', on_delete=django.db.models.deletion.CASCADE, to='core.businesscode', to_field='code'),
        ),
        migrations.AddField(
            model_name='mftuser',
            name='business',
            field=models.ForeignKey(default='NAHAB', on_delete=django.db.models.deletion.CASCADE, to='core.businesscode', to_field='code'),
        ),
        migrations.AddField(
            model_name='mftusertemp',
            name='business',
            field=models.ForeignKey(default='NAHAB', on_delete=django.db.models.deletion.CASCADE, to='core.businesscode', to_field='code'),
        ),
        migrations.AddField(
            model_name='operationbusiness',
            name='access_on_bus',
            field=models.ForeignKey(default='NAHHB', on_delete=django.db.models.deletion.CASCADE, to='core.businesscode', to_field='code'),
        ),
    ]
