# Generated by Django 3.1.4 on 2022-08-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20220822_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iscuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='iscuser',
            name='mobilephone',
            field=models.DecimalField(decimal_places=0, default=9123456789, max_digits=11),
        ),
        migrations.AddField(
            model_name='iscuser',
            name='officephone',
            field=models.DecimalField(decimal_places=0, default=12345678, max_digits=8),
        ),
    ]
