# Generated by Django 3.1.4 on 2022-08-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20220823_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscdepartmentcode',
            name='access_type',
            field=models.ForeignKey(default='OPERATION', on_delete=django.db.models.deletion.CASCADE, to='core.iscuseraccesscode', to_field='code'),
        ),
    ]
