# Generated by Django 3.1.4 on 2022-08-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_iscdepartmentcode_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscode',
            name='address',
            field=models.CharField(default='/DATA', max_length=10),
        ),
    ]
