# Generated by Django 3.1.4 on 2022-08-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_businesscode_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankidentifiercode',
            name='directory_name',
            field=models.CharField(default='_ISC', max_length=50),
        ),
    ]
