# Generated by Django 3.1.4 on 2022-08-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_bankidentifiercode_directory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscode',
            name='address',
            field=models.CharField(default='/DATA', max_length=100),
        ),
    ]
