# Generated by Django 3.1.4 on 2022-09-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20220830_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscode',
            name='code',
            field=models.CharField(default='...', max_length=20, unique=True),
        ),
    ]
