# Generated by Django 3.1.4 on 2022-09-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20220907_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='absolute_path',
            new_name='relative_path',
        ),
    ]
