# Generated by Django 3.1.4 on 2022-09-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20220907_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscuser',
            name='mobilephone',
            field=models.DecimalField(decimal_places=0, default=9123456789, max_digits=12),
        ),
        migrations.AlterField(
            model_name='iscuser',
            name='officephone',
            field=models.DecimalField(decimal_places=0, default=12345678, max_digits=10),
        ),
    ]
