# Generated by Django 3.1.4 on 2022-09-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20220910_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankidentifiercode',
            name='code',
            field=models.CharField(default='_ISC', max_length=20, unique=True),
        ),
    ]
