# Generated by Django 3.1.4 on 2022-10-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_mftusertemp_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mftuser',
            name='ipaddr',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='mftusertemp',
            name='ipaddr',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
