# Generated by Django 3.1.4 on 2022-10-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20221012_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='children',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='directory',
            name='relative_path',
            field=models.CharField(max_length=500),
        ),
        migrations.RemoveField(
            model_name='mftuser',
            name='business',
        ),
        migrations.AddField(
            model_name='mftuser',
            name='business',
            field=models.ManyToManyField(to='core.BusinessCode'),
        ),
        migrations.RemoveField(
            model_name='mftusertemp',
            name='business',
        ),
        migrations.AddField(
            model_name='mftusertemp',
            name='business',
            field=models.ManyToManyField(to='core.BusinessCode'),
        ),
    ]
