# Generated by Django 3.1.4 on 2022-11-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20221017_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationbusiness',
            name='owned_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
