# Generated by Django 3.1.4 on 2022-12-07 06:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_operationbusiness_owned_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readytoexport',
            name='export',
            field=models.FileField(default='username.zip', storage=core.models.OverwriteStorage(), upload_to='exports/'),
        ),
    ]
