# Generated by Django 3.1.4 on 2023-01-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20221207_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='readytoexport',
            name='number_of_downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='readytoexport',
            name='number_of_exports',
            field=models.IntegerField(default=1),
        ),
    ]
