# Generated by Django 3.1.4 on 2023-01-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20230101_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readytoexport',
            name='is_downloaded',
        ),
    ]
