# Generated by Django 3.1.4 on 2023-07-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_readytoexport_is_downloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('code', models.CharField(default='BANK', max_length=100, unique=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codingtype', to_field='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='customeraccesscode',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='customeraccesstype',
            name='type_id',
        ),
        migrations.DeleteModel(
            name='CustomerAccess',
        ),
        migrations.DeleteModel(
            name='CustomerAccessCode',
        ),
        migrations.DeleteModel(
            name='CustomerAccessType',
        ),
    ]
