# Generated by Django 3.1.4 on 2023-07-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20230729_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankidentifiercode',
            name='organization_type',
            field=models.ForeignKey(default='STATE_BANK', on_delete=django.db.models.deletion.CASCADE, to='core.organizationtype', to_field='code'),
        ),
    ]
