# Generated by Django 3.1.4 on 2023-07-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_bankidentifiercode_organization_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscode',
            old_name='address',
            new_name='origin_address',
        ),
        migrations.AddField(
            model_name='businesscode',
            name='remote_address',
            field=models.CharField(default='/SMB', max_length=100),
        ),
    ]
