# Generated by Django 4.2.3 on 2023-07-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20230729_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
