# Generated by Django 3.2.13 on 2023-07-31 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_iscuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscode',
            name='remote_address',
            field=models.CharField(default='resource:sftp://', max_length=100),
        ),
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('code', models.CharField(default='example.com', max_length=250, unique=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codingtype', to_field='type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
