# Generated by Django 3.2.13 on 2023-07-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20230731_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankidentifiercode',
            name='sub_domain',
            field=models.ForeignKey(blank=True, default='nibn.ir', on_delete=django.db.models.deletion.CASCADE, to='core.domainname', to_field='code'),
        ),
    ]
