# Generated by Django 3.2.13 on 2023-08-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_bankidentifiercode_sub_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscode',
            name='remote_address',
            field=models.CharField(default='resource:sftp://SETAD/SITA', max_length=100),
        ),
    ]
