# Generated by Django 3.2.13 on 2023-09-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20230829_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='mftuser',
            name='password_expiration_interval',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
