# Generated by Django 3.2.13 on 2023-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_mftuser_password_expiration_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='mftuser',
            name='owned_business',
            field=models.ManyToManyField(related_name='owned_business', to='core.BusinessCode'),
        ),
        migrations.AddField(
            model_name='mftuser',
            name='used_business',
            field=models.ManyToManyField(related_name='used_business', to='core.BusinessCode'),
        ),
    ]
