# Generated by Django 3.2.13 on 2023-12-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20231212_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mftuser',
            name='business',
        ),
        migrations.DeleteModel(
            name='MftUserTemp',
        ),
    ]
