# Generated by Django 3.2.13 on 2024-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20231212_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscode',
            name='code',
            field=models.CharField(default='...', max_length=50, unique=True),
        ),
    ]
