# Generated by Django 3.2.13 on 2024-03-07 10:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0021_auto_20230824_1308'),
        ('core', '0082_alter_businesscode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetadUserInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(default=None, max_length=50)),
                ('confirm_or_reject', models.CharField(default='UNDEFINED', max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('officephone', models.CharField(max_length=100)),
                ('mobilephone', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuser')),
                ('invoice_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicetype', to_field='code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
