# Generated by Django 3.2.13 on 2024-03-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setaduserinvoice',
            name='business',
            field=models.CharField(max_length=10000),
        ),
    ]
