# Generated by Django 3.2.13 on 2024-03-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setad', '0002_alter_setaduserinvoice_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setaduserinvoice',
            name='business',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
