# Generated by Django 3.2.13 on 2024-03-08 12:26

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_businesscode_code'),
        ('setad', '0003_alter_setaduserinvoice_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyToExportSetad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webuser', models.FileField(default='template.xml', storage=core.models.OverwriteStorage(), upload_to='exports/setad/')),
                ('paths', models.FileField(default='paths.csv', storage=core.models.OverwriteStorage(), upload_to='exports/setad/')),
                ('number_of_exports', models.IntegerField(default=1)),
                ('number_of_downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuser')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setad.setaduserinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='AzmoonDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.IntegerField(default=0)),
                ('children', models.CharField(blank=True, max_length=500)),
                ('absolute_path', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(default='NAHAB', on_delete=django.db.models.deletion.CASCADE, to='core.businesscode', to_field='code')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuser')),
                ('index_code', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='core.directoryindexcode', to_field='code')),
            ],
        ),
    ]
