# Generated by Django 3.2.13 on 2024-03-08 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_businesscode_code'),
        ('setad', '0004_azmoondirectory_readytoexportsetad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzmoonDirectoryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(default=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuser')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setad.azmoondirectory')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setad.setaduserinvoice')),
            ],
        ),
    ]
