# Generated by Django 3.2.13 on 2024-05-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setad', '0005_azmoondirectorypermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='setaduserinvoice',
            name='group_type',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
