# Generated by Django 3.1.4 on 2022-11-22 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_operationbusiness_owned_by_user'),
        ('invoice', '0002_auto_20221009_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('code', models.CharField(default='DEFAULT', max_length=20, unique=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codingtype', to_field='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicetype'),
        ),
    ]
