# Generated by Django 3.1.4 on 2022-11-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20221122_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='used_business',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
