# Generated by Django 3.1.4 on 2022-12-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_used_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='serial_number',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
