# Generated by Django 3.1.4 on 2022-12-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
