# Generated by Django 3.1.4 on 2022-12-06 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_operationbusiness_owned_by_user'),
        ('invoice', '0007_invoice_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='processed',
        ),
        migrations.AddField(
            model_name='invoice',
            name='confirm_or_reject',
            field=models.CharField(default='UNDEFINED', max_length=10),
        ),
        migrations.CreateModel(
            name='PreInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(default=None, max_length=50)),
                ('confirm_or_reject', models.CharField(default='UNDEFINED', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('directories_list', models.CharField(default='', max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iscuser')),
                ('invoice_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicetype', to_field='code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
