# Generated by Django 3.1.4 on 2022-12-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20221206_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetype',
            name='serial_prefix',
            field=models.CharField(default='SITA', max_length=20),
        ),
    ]
