# Generated by Django 3.1.4 on 2022-12-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20221217_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='permissions_list',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
