# Generated by Django 3.1.4 on 2023-01-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_invoice_permissions_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='permissions_list',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
