# Generated by Django 3.1.4 on 2023-05-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20230122_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preinvoice',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
