# Generated by Django 3.1.4 on 2023-05-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_auto_20230518_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinvoice',
            name='directories_list',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
