# Generated by Django 3.1.4 on 2023-06-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20230531_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='permissions_list',
            field=models.CharField(blank=True, default='', max_length=1000000),
        ),
    ]
