# Generated by Django 3.2.13 on 2023-08-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_auto_20230627_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinvoice',
            name='directories_list',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
