# Generated by Django 3.2.13 on 2023-08-24 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_businesscode_foreign_address'),
        ('invoice', '0020_auto_20230824_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='mftuser_fk',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mftuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mftuser'),
        ),
    ]
